// src/components/TermsAndConditions.tsx
import React from "react";

const Terms = () => {
  return (
    <div className="max-w-4xl mt-15 mx-auto px-4 sm:px-8 lg:px-8 py-12 md:py-16 font-sans text-gray-800 dark:text-gray-200 leading-relaxed">
      <header className="text-center mb-12">
        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 dark:text-white mb-4">
          Spares Connect LLP – Terms & Conditions of Use
        </h1>
        <p className="text-lg md:text-xl text-gray-600 dark:text-gray-400">
          Effective Date: 20th January 2026
        </p>
      </header>

      <main className="space-y-16">
        {/* ARTICLE 1 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 1: LEGAL STATUS, ELECTRONIC RECORD & BINDING NATURE
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>1.1</strong> These Terms and Conditions of Use ("Terms")
              constitute an electronic record in accordance with the provisions
              of the Information Technology Act, 2000 and the rules made
              thereunder, including but not limited to the Information
              Technology (Intermediary Guidelines and Digital Media Ethics Code)
              Rules, 2021. This electronic record is generated by a computer
              system and does not require any physical or digital signature.
            </p>

            <p>
              <strong>1.2</strong> These Terms form a legally binding agreement
              between Spares Connect LLP, a limited liability partnership
              incorporated under the laws of India, having its registered office
              in India ("Spares Connect", "Company", "we", "us", "our") and any
              person or business entity accessing or using the digital
              marketplace platform operated by the Company, including its
              website, mobile applications, APIs, dashboards, integrations and
              related services (collectively, the "Platform") ("User", "you",
              "your").
            </p>

            <p>
              <strong>1.3</strong> By accessing, registering on, browsing or
              transacting through the Platform or by clicking "I Agree",
              "Accept" or any similar mechanism, the User expressly acknowledges
              and agrees that:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>they have read and understood these Terms;</li>
              <li>
                they consent to be bound by these Terms, all policies referenced
                herein and all applicable laws;
              </li>
              <li>
                their continued access to or use of the Platform constitutes
                valid and enforceable acceptance of these Terms.
              </li>
            </ul>

            <p>
              <strong>1.4</strong> These Terms shall be read in conjunction with
              and are subject to the Privacy Policy, Buyer Policy, Seller
              Policy, Refund, Return & Cancellation Policy and any other
              policies published by Spares Connect from time to time, all of
              which form an integral part of this agreement.
            </p>
          </div>
        </section>

        {/* ARTICLE 2 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 2: DEFINITIONS & INTERPRETATION
          </h2>

          <h3 className="text-xl md:text-2xl font-semibold mt-8 mb-5">
            2.1 Definitions
          </h3>
          <p className="mb-4">
            For the purposes of these Terms, unless the context otherwise
            requires:
          </p>

          <dl className="space-y-5 text-base md:text-lg">
            <div>
              <dt className="font-semibold inline">"Company"</dt>
              <dd className="ml-2 inline">
                means Spares Connect LLP, a limited liability partnership
                incorporated under the laws of India.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Platform"</dt>
              <dd className="ml-2 inline">
                means the digital business-to-business marketplace operated by
                the Company, including its website, mobile applications, APIs,
                dashboards, integrations, software infrastructure and related
                services.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"User"</dt>
              <dd className="ml-2 inline">
                means any business entity, professional or legally recognised
                commercial establishment, including its owners, partners,
                directors, employees, agents or authorized representatives, that
                access or use the Platform in any manner.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Buyer"</dt>
              <dd className="ml-2 inline">
                means automobile mechanics, workshops, garages, service centers,
                fleet operators or other commercial entities procuring
                automobile spare parts or related goods for business purposes
                through the Platform.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Seller"</dt>
              <dd className="ml-2 inline">
                means independent third-party suppliers, distributors,
                wholesalers, retailers or manufacturers listing, quoting or
                supplying automobile spare parts or related goods through the
                Platform.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Transaction"</dt>
              <dd className="ml-2 inline">
                means any enquiry, quotation, negotiation, order placement,
                payment initiation, delivery coordination, return request or
                related interaction conducted between a Buyer and a Seller
                through or facilitated by the Platform. For the avoidance of
                doubt, the Company is not a party to any Transaction.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Services"</dt>
              <dd className="ml-2 inline">
                means the technology services provided by the Company through
                the Platform, including discovery, communication tools,
                quotation facilitation, status tracking and related features.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Content"</dt>
              <dd className="ml-2 inline">
                means all data, text, images, audio, documents, listings,
                communications and other materials uploaded, submitted or
                generated by Users on the Platform.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Policies"</dt>
              <dd className="ml-2 inline">
                means all policies published by the Company from time to time,
                including the Privacy Policy, Buyer Policy, Seller Policy,
                Refund, Return & Cancellation Policy and any other guidelines or
                notices.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Payment Partner"</dt>
              <dd className="ml-2 inline">
                means any RBI-regulated bank, payment aggregator or financial
                institution integrated with the Platform for payment
                facilitation.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Logistics Partner"</dt>
              <dd className="ml-2 inline">
                means any third-party courier, transporter or delivery service
                provider engaged by Sellers or Buyers.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Applicable Law"</dt>
              <dd className="ml-2 inline">
                means all laws, statutes, rules, regulations, notifications,
                guidelines and governmental orders applicable in India,
                including amendments thereto.
              </dd>
            </div>
            <div>
              <dt className="font-semibold inline">"Force Majeure Event"</dt>
              <dd className="ml-2 inline">
                means any event beyond reasonable control, including natural
                disasters, acts of government, strikes, technical failures or
                disruptions in banking or network systems.
              </dd>
            </div>
          </dl>

          <h3 className="text-xl md:text-2xl font-semibold mt-10 mb-5">
            2.2 Interpretation
          </h3>
          <p className="mb-4">Unless the context otherwise requires:</p>
          <ul className="list-disc pl-6 md:pl-8 space-y-2 text-base md:text-lg">
            <li>
              words in the singular shall include the plural and vice versa;
            </li>
            <li> references to any gender shall include all genders;</li>
            <li>
              the words "include", "includes" and "including" shall be deemed to
              be followed by "without limitation";
            </li>
            <li>
              references to writing or written form include electronic
              communications;
            </li>
            <li>
              headings are inserted for convenience only and shall not affect
              interpretation;
            </li>
            <li>
              references to any law include amendments, reenactments or
              replacements thereof;
            </li>
            <li>
              in case of conflict between these Terms and any Policy, these
              Terms shall prevail unless expressly stated otherwise;
            </li>
            <li>
              the English version of these Terms shall prevail over any
              translation.
            </li>
          </ul>
        </section>

        {/* ARTICLE 3 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 3: PLATFORM ROLE & INTERMEDIARY STATUS
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>3.1</strong> Spares Connect LLP operates strictly as an
              intermediary within the meaning of Section 2(1)(w) and Section 79
              of the Information Technology Act, 2000 and the rules made
              thereunder. The Company provides a technology platform that
              enables Buyers and Sellers to discover, communicate, exchange
              quotations and coordinate Transactions.
            </p>

            <p>
              <strong>3.2</strong> The Platform is limited to facilitating:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>discovery of Sellers by Buyers and vice versa;</li>
              <li>communication and exchange of information between Users;</li>
              <li>quotation comparison and order coordination;</li>
              <li>status tracking and ancillary technological tools.</li>
            </ul>

            <p>
              <strong>3.3</strong> For the avoidance of doubt, Spares Connect:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                does not own, stock, store, warehouse, package or inspect any
                goods;
              </li>
              <li>
                does not manufacture, import, export, distribute, sell or resell
                any products;
              </li>
              <li>
                does not set, control, influence or determine pricing,
                discounts, availability or commercial terms;
              </li>
              <li>
                does not assume title, ownership, possession, custody or risk in
                respect of any goods at any time;
              </li>
              <li>
                does not provide warranties, guarantees, certifications or
                assurances of any kind, express or implied;
              </li>
              <li>
                does not verify product quality, legality, compatibility, safety
                or fitness for any particular purpose;
              </li>
              <li>
                does not provide installation, technical advice or after-sales
                service in relation to any products.
              </li>
            </ul>
            <p>
              <strong>3.4</strong> All Transactions conducted on the Platform
              constitute{" "}
              <strong>independent, principal-to-principal contracts</strong>{" "}
              exclusively between Buyers and Sellers. Spares Connect is{" "}
              <strong>not a party</strong> to any such contract and has no
              responsibility or liability in relation to the formation,
              performance, breach or termination of such contracts
            </p>
            <p>
              <strong>3.5</strong> Nothing contained in these Terms shall be
              deemed to create any agency, partnership, joint venture,
              employment, fiduciary or representative relationship between
              Spares Connect and any User. Users act solely in their own
              independent commercial capacity.
            </p>
            <p>
              <strong>3.6</strong> Any facilitation of payments, logistics
              coordination or communication by the Platform is purely incidental
              to its role as an intermediary and shall not be construed as
              assumption of responsibility, control or liability over
              Transactions, goods or services.
            </p>
            <p>
              <strong>3.7</strong> Spares Connect does not exercise editorial
              control over User-generated content or listings and shall not be
              obligated to monitor, pre-screen or verify content, except as
              required under Applicable Law.
            </p>
          </div>
        </section>

        {/* ARTICLE 4 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 4: ELIGIBILITY & B2B USE
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>4.1</strong> The Platform is intended exclusively for{" "}
              <strong>business-to-business (B2B)</strong> commercial use and is
              designed solely for professional automobile mechanics, workshops,
              garages, service centres, fleet operators, spare-parts suppliers
              and other business entities engaged in automotive trade or
              services.
            </p>

            <p>
              <strong>4.2</strong> By accessing or using the Platform, each User
              represents and warrants that:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                they are legally competent to enter into binding contracts under
                Applicable Law;
              </li>
              <li>
                they are accessing the Platform strictly for commercial, trade,
                professional, resale, repair, servicing or fleet-maintenance
                purposes;
              </li>
              <li>
                they are not accessing the Platform for personal, household or
                individual consumer use;
              </li>
              <li>
                any Transactions conducted through the Platform are in the
                course of business or profession.
              </li>
            </ul>

            <p>
              <strong>4.3</strong> The Company does not offer goods or services
              for personal consumption and does not knowingly permit use of the
              Platform by individual consumers. Any access inconsistent with the
              business-use intent of the Platform shall be deemed unauthorised.
            </p>

            <p>
              <strong>4.4</strong> The Company reserves the right, at its sole
              discretion, to:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                require Users to provide business identification, trade
                credentials or other supporting information;
              </li>
              <li>
                refuse, suspend or terminate access where eligibility
                requirements are not met or are misrepresented;
              </li>
              <li>restrict features or Transactions pending verification.</li>
            </ul>
            <p>
              <strong>4.5</strong> Access to and use of the Platform is strictly
              prohibited for individuals under eighteen (18) years of age. Where
              a User is a business entity, access shall be permitted only
              through authorized representatives acting within the scope of
              their authority and the entity shall be fully responsible for
              their actions.
            </p>
          </div>
        </section>

        {/* ARTICLE 5 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 5: USER REGISTRATION & ACCOUNT RESPONSIBILITY
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>5.1</strong> To access or use the Platform, Users must
              register an account and provide accurate, complete and current
              business, professional and contact information as may be required
              by the Company from time to time.
            </p>

            <p>
              <strong>5.2</strong> Users represent and warrant that all
              information submitted during registration and thereafter is true,
              correct and not misleading. Users shall promptly update their
              account information to reflect any changes, including changes in
              business ownership, legal status, licenses, registrations, contact
              details or authorized representatives.
            </p>
            <p>
              <strong>5.3</strong> The Company reserves the right to conduct
              verification, re-verification or due diligence of User information
              at any time, including requesting supporting documentation,
              conducting background checks or suspending access pending
              verification.
            </p>
            <p>
              <strong>5.4</strong> Users are solely and fully responsible for:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                maintaining the confidentiality and security of their account
                credentials;
              </li>
              <li>
                all activities conducted through their account, whether by
                owners, employees, agents or authorized representatives;
              </li>
              <li>
                ensuring that only duly authorized persons access the Platform
                on their behalf;
              </li>
              <li>
                the accuracy, legality and completeness of all data, content and
                information submitted through their account.
              </li>
            </ul>

            <p>
              <strong>5.5</strong> Any act or omission carried out through a
              User's account shall be deemed to have been authorized by the User
              and the User shall be fully liable for the same.
            </p>

            <p>
              <strong>5.6</strong> The Company may, at its sole discretion and
              without liability, suspend, restrict or terminate any account, in
              whole or in part, with or without notice, where it reasonably
              believes that:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                the account is involved in fraud, misuse or suspicious activity;
              </li>
              <li>the User has breached these Terms or any Policy;</li>
              <li>
                continued access poses legal, regulatory, financial or
                reputational risk to the Company;
              </li>
              <li>
                the User has attempted to circumvent the Platform or its
                safeguards.
              </li>
            </ul>
            <p>
              <strong>5.7</strong> Suspension or termination of an account shall
              not affect any accrued rights, obligations or liabilities arising
              prior to such action.
            </p>
          </div>
        </section>

        {/* ARTICLE 6 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 6: PLATFORM SERVICES & LIMITATIONS
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>6.1</strong> The Platform provides technology-based
              services intended to facilitate interactions between Buyers and
              Sellers, which may include, without limitation:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                vehicle-based and category-based discovery of spare parts;
              </li>
              <li>supplier identification and matching;</li>
              <li>quotation requests, comparisons and order coordination;</li>
              <li>communication tools enabling Buyer-Seller interaction;</li>
              <li>
                transaction status tracking and related informational tools.
              </li>
            </ul>

            <p>
              <strong>6.2</strong> The Services provided by the Platform are
              limited to facilitating information exchange and coordination and
              are provided on a best-effort basis. The Company does not
              guarantee that any Transaction will be successfully concluded.
            </p>
            <p>
              <strong>6.3</strong> Spares Connect does not warrant or guarantee:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                the availability, accuracy, completeness or reliability of
                listings, quotations or Content;
              </li>
              <li>
                product availability, pricing, discounts or commercial terms;
              </li>
              <li>
                delivery timelines, logistics performance or shipment outcomes;
              </li>
              <li>Seller performance, conduct or fulfilment;</li>
              <li>
                uninterrupted, timely, secure or error-free operation of the
                Platform.
              </li>
            </ul>
            <p>
              <strong>6.4</strong> The Company reserves the right, at its sole
              discretion, to modify, suspend, restrict or discontinue any
              feature, functionality or aspect of the Platform or Services,
              temporarily or permanently, without liability.
            </p>

            <p>
              <strong>6.5</strong> The Platform does not provide professional,
              technical, mechanical, legal or commercial advice and Users shall
              not rely on the Platform or any Content as a substitute for
              independent verification or professional judgment
            </p>
          </div>
        </section>

        {/* ARTICLE 7 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 7: PAYMENTS & FINANCIAL FLOWS
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>7.1</strong> Payments for Transactions conducted through
              the Platform may be:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                made directly between Buyers and Sellers using mutually agreed
                payment methods; or
              </li>
              <li>
                facilitated through third-party payment partners, including
                banks or payment aggregators, that are regulated by the Reserve
                Bank of India ("RBI").
              </li>
            </ul>

            <p>
              <strong>7.2</strong> The Company acts solely as a technology
              facilitator in relation to payments. Unless expressly notified
              otherwise in writing, Spares Connect:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                does not collect, receive, hold, store or control Buyer funds;
              </li>
              <li>
                does not operate or manage escrow, nodal or trust accounts;
              </li>
              <li>
                does not assume custody, ownership or risk in respect of any
                monies at any time.
              </li>
            </ul>
            <p>
              <strong>7.3</strong> Spares Connect is not a bank, non-banking
              financial company (NBFC), payment aggregator, trustee, escrow
              agent or fiduciary and does not provide any regulated financial
              service.
            </p>
            <p>
              <strong>7.4</strong> Any payment facilitation provided through the
              Platform is subject to the terms, conditions and operational
              processes of the relevant payment partner. Spares Connect shall
              not be responsible or liable for:
            </p>

            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>payment failures, reversals or declines;</li>
              <li>bank or UPI downtime;</li>
              <li>settlement delays, chargebacks or technical issues;</li>
              <li>
                errors or omissions attributable to payment partners or
                financial institutions.
              </li>
            </ul>

            <p>
              <strong>7.5</strong> In the event of chargebacks, disputes,
              reversals or suspected fraudulent transactions, the Company
              reserves the right to:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>suspend or reverse the relevant Transaction;</li>
              <li>withhold, deduct or adjust amounts payable to Sellers;</li>
              <li>
                cooperate with banks, payment partners or authorities for
                investigation and resolution.
              </li>
            </ul>
            <p>
              <strong>7.6</strong>The Company may, in future, introduce
              additional payment mechanisms, including escrow arrangements,
              nodal accounts, split settlements or other compliant structures,
              strictly in accordance with Applicable Law and RBI guidelines. Any
              such mechanisms shall be governed by additional terms or notices
              and continued use of the Platform shall constitute acceptance
              thereof.
            </p>
            <h3 className="text-xl md:text-2xl font-semibold mt-10 mb-5">
              7.7 Invoicing & Tax Responsibility
            </h3>
            <p>
              <strong>7.7.1</strong> Spares Connect does not sell goods and does
              not issue tax invoices for products supplied by Sellers. Each
              Seller is solely responsible for issuing valid tax invoices to
              Buyers for goods supplied through the Platform, in compliance with
              applicable GST and tax laws.
            </p>
            <p>
              <strong>7.7.2</strong> Spares Connect may issue tax invoices,
              debit notes, or receipts <strong>only</strong> in respect of
              platform fees, subscription charges, service fees, or logistics
              facilitation charges (where applicable), and such invoices shall
              not be construed as invoices for the underlying goods.
            </p>
            <p>
              <strong>7.7.3</strong> Where any amount, including delivery or
              logistics charges, is collected by Spares Connect on behalf of
              Sellers or third-party delivery partners, such collection shall be
              deemed to be on a pass-through basis, and the obligation to issue
              tax invoices shall rest with the respective Seller or delivery
              partner, unless otherwise required by Applicable Law.
            </p>
            <p>
              <strong>7.7.4</strong> Buyers acknowledge that a single order may
              involve multiple invoices issued by different parties, and Spares
              Connect shall not be responsible for discrepancies arising from
              Seller-issued invoices
            </p>
            <p>
              <strong>7.7.5</strong> Spares Connect shall not be liable for any
              tax non-compliance, misclassification, under-reporting, or
              invoicing errors attributable to Sellers or third-party service
              providers.
            </p>
          </div>
        </section>

        {/* ARTICLE 8 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 8: LOGISTICS & DELIVERY
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>8.1</strong> Delivery of goods shall be arranged either
              directly by Sellers or through third-party logistics providers
              engaged by Sellers or Buyers. Spares Connect does not provide
              transportation, courier, warehousing or delivery services.
            </p>
            <p>
              <strong>8.2</strong> Spares Connect does not take custody,
              possession, control or ownership of any goods at any point. The
              Company does not act as a carrier, freight forwarder, bailee or
              insurer of goods.
            </p>
            <p>
              <strong>8.3</strong> Risk of loss, damage, theft or delay in
              respect of goods shall pass in accordance with the Seller's terms
              or, in the absence of specific agreement, upon dispatch or
              handover of goods to the logistics provider.
            </p>
            <p>
              <strong>8.4</strong>Spares Connect shall not be liable for:
            </p>

            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>delays in delivery;</li>
              <li>loss, damage or deterioration of goods during transit;</li>
              <li>actions or omissions of logistics providers;</li>
              <li>
                force majeure events affecting transportation or delivery.
              </li>
            </ul>

            <p>
              <strong>8.5</strong> Buyers are responsible for inspecting goods
              immediately upon delivery and raising any issues directly with the
              Seller or logistics provider, in accordance with the applicable
              return or dispute process.
            </p>
            <p>
              <strong>8.6</strong> The Company may, in a phased manner and at
              its sole discretion, integrate third-party logistics providers,
              delivery partners, aggregators or technology-enabled
              transportation service providers ("Delivery Partners") to enable
              delivery coordination, tracking or facilitation on the Platform.
            </p>
            <p>
              <strong>8.7</strong> Any such integration shall be limited to
              technological facilitation and coordination only. Spares Connect
              does not provide, operate, manage or control delivery, courier,
              transportation, warehousing or insurance services, whether
              directly or indirectly.
            </p>
            <p>
              <strong>8.8</strong> Where Delivery Partners are integrated
              through the Platform:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                such Delivery Partners shall act as independent third parties;
              </li>
              <li>
                delivery services shall be governed by the terms and conditions
                of the respective Delivery Partner and/or Seller;
              </li>
              <li>
                Spares Connect shall not be responsible or liable for delays,
                loss, damage, theft, non-performance, service deficiencies or
                misconduct attributable to Delivery Partners;
              </li>
              <li>
                risk of loss or damage to goods shall remain with the Seller
                and/or Buyer in accordance with their agreed terms or Applicable
                Law.
              </li>
            </ul>
            <p>
              <strong>8.9</strong>The Company reserves the right to add, modify,
              replace, suspend or discontinue Delivery Partners or
              delivery-related features at any time, without liability.
              Continued use of the Platform following such changes shall
              constitute acceptance of the same.
            </p>
          </div>
        </section>

        {/* ARTICLE 9 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 9: INTELLECTUAL PROPERTY
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>9.1</strong> All intellectual property rights in and to
              the Platform, including but not limited to the software, source
              code, object code, databases, algorithms, workflows, business
              logic, user interfaces, designs, layouts, text, graphics,
              trademarks, logos, trade names, domain names and all related
              content (collectively, "Platform IP"), are owned exclusively by or
              licensed to <strong>Spares Connect LLP.</strong>
            </p>
            <p>
              <strong>9.2</strong> Except for the limited right to access and
              use the Platform in accordance with these Terms, no right, title
              or interest in the Platform IP is transferred to any User. Users
              shall not copy, reproduce, modify, distribute, reverse engineer,
              decompile, scrape, extract data from or commercially exploit any
              part of the Platform or Platform IP without prior written consent
              of the Company.
            </p>
            <p>
              <strong>9.3</strong> Users retain ownership of intellectual
              property rights in content, data, images, audio, documents or
              other materials submitted, uploaded or generated by them on the
              Platform ("User Content").
            </p>
            <p>
              <strong>9.4</strong>By submitting User Content, Users grant Spares
              Connect a{" "}
              <strong>
                non-exclusive, worldwide, royalty-free, perpetual, irrevocable
                and sublicensable license
              </strong>{" "}
              to host, store, reproduce, modify, adapt, publish, translate,
              distribute, analyze and display such User Content{" "}
              <strong>
                to the Company, its affiliates, successors, assigns and
                permitted sublicensees,
              </strong>
              solely for the purposes of operating, improving, securing,
              administering and promoting the Platform, including compliance,
              analytics, backups, internal use and dispute resolution.
            </p>

            <p>
              <strong>9.5</strong> Users represent and warrant that they have
              all necessary rights, licences and permissions to submit User
              Content and that such content does not infringe any third-party
              intellectual property or proprietary rights.
            </p>
            <p>
              <strong>9.6</strong> The Company reserves the right to remove,
              disable access to or restrict User Content that infringes
              intellectual property rights, violates Applicable Law or breaches
              these Terms, without liability.
            </p>
            <p>
              <strong>9.7</strong> The provisions of this Article shall survive
              suspension or termination of User accounts and continued use of
              User Content as permitted herein.
            </p>
          </div>
        </section>

        {/* ARTICLE 10 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 10: DATA PROTECTION & PRIVACY
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>10.1</strong> Spares Connect processes personal data and
              business data in accordance with the Information Technology Act,
              2000, the Information Technology (Reasonable Security Practices
              and Procedures and Sensitive Personal Data or Information) Rules,
              2011 and the Digital Personal Data Protection Act, 2023 ("DPDP
              Act") and other Applicable Law.
            </p>
            <p>
              <strong>10.2</strong> For the purposes of data processing:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                Spares Connect acts as a <strong>Data Fiduciary</strong> in
                respect of data collected and processed for Platform operations,
                user registration, verification, security, analytics, fraud
                prevention and compliance;
              </li>
              <li>
                Spares Connect acts as a <strong>Data Processor</strong> in
                respect of transactional data exchanged between Buyers and
                Sellers strictly for the purpose of facilitating Transactions
                through the Platform.
              </li>
            </ul>
            <p>
              <strong>10.3</strong> Users acknowledge and agree that their data
              may be shared with other Users, payment partners, logistics
              partners, technology service providers and governmental or
              regulatory authorities, solely for purposes of transaction
              fulfilment, Platform operation, legal compliance and enforcement.
            </p>
            <p>
              <strong>10.4</strong>Data shall be processed only for lawful and
              specified purposes, retained only for as long as necessary and
              protected using reasonable security practices, in accordance with
              the Privacy Policy.
            </p>

            <p>
              <strong>10.5</strong> The rights of Data Principals, including
              rights relating to access, correction, erasure, consent withdrawal
              and grievance redressal, shall be governed by the Privacy Policy
              published on the Platform.
            </p>
            <p>
              <strong>10.6</strong> This Article shall be read in conjunction
              with the Privacy Policy, which forms an integral part of these
              Terms. In the event of any inconsistency, the Privacy Policy shall
              prevail in relation to data protection matters.
            </p>
          </div>
        </section>

        {/* ARTICLE 11 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 11: PROHIBITED CONDUCT
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>11.1</strong> Users shall use the Platform strictly in
              accordance with these Terms, applicable Policies and Applicable
              Law.
            </p>
            <p>
              <strong>11.2</strong> Users shall not, directly or indirectly,
              engage in any of the following prohibited conduct:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                misuse, abuse or interfere with the normal operation of the
                Platform;
              </li>
              <li>
                attempt to circumvent, bypass or avoid the Platform, including
                by engaging in off-platform transactions with other Users
                introduced through the Platform;
              </li>
              <li>
                create false, misleading, duplicate or unauthorized accounts;
              </li>
              <li>
                submit inaccurate, deceptive or fraudulent information or
                content;
              </li>
              <li>
                engage in any fraudulent activity, payment abuse, chargeback
                manipulation or misrepresentation;
              </li>
              <li>
                scrape, harvest, extract, copy or misuse data, listings, contact
                information or Content from the Platform;
              </li>
              <li>
                misuse, disclose, sell or exploit personal data or confidential
                information of other Users;
              </li>
              <li>
                infringe intellectual property rights of the Company or any
                third party;
              </li>
              <li>
                harass, threaten, abuse or harm other Users, delivery partners
                or Company personnel;
              </li>
              <li>
                upload malware, viruses or engage in activities that compromise
                Platform security;
              </li>
              <li>
                use the Platform for any unlawful, prohibited or unauthorized
                purpose.
              </li>
            </ul>
            <p>
              <strong>11.3</strong> Any attempt to engage in prohibited conduct,
              whether successful or not, shall constitute a breach of these
              Terms.
            </p>
            <p>
              <strong>11.4</strong> The Company reserves the right, at its sole
              discretion and without liability, to investigate, restrict,
              suspend or terminate User access, remove content, withhold
              payments or take appropriate legal action in response to
              prohibited conduct or suspected violations.
            </p>

            <p>
              <strong>11.5</strong> Enforcement of actions taken under this
              Article shall be without prejudice to any other rights or remedies
              available to the Company under law or equity.
            </p>
            <h3 className="text-xl md:text-2xl font-semibold mt-10 mb-5">
              11.6 Fraud Prevention & Security Advisory
            </h3>

            <p>
              <strong>11.6.1</strong> Users are advised that Spares Connect does
              not request, and shall never request, sensitive financial
              information such as passwords, OTPs, UPI PINs, card details, CVV
              numbers, or bank account credentials through phone calls,
              messages, emails, or any unofficial communication channels.
            </p>
            <p>
              <strong>11.6.2</strong> Any person soliciting such information
              while representing themselves as Spares Connect shall be deemed
              unauthorised and fraudulent.
            </p>
            <p>
              <strong>11.6.3</strong> Users shall be solely responsible for
              maintaining the confidentiality of their credentials and for any
              loss, damage, or unauthorised transactions arising from disclosure
              of such information.
            </p>
            <p>
              <strong>11.6.4</strong> Spares Connect shall not be liable for
              losses arising from phishing, impersonation, social engineering
              attacks, or unauthorised access resulting from User negligence or
              failure to follow security advisories.
            </p>
          </div>
        </section>

        {/* ARTICLE 12 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 12: SUSPENSION & TERMINATION
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>12.1</strong> The Company may, at its sole discretion and
              without liability, suspend, restrict or terminate a User's access
              to the Platform, in whole or in part, with or without notice,
              where the Company reasonably believes that:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                the User has breached these Terms or any applicable Policy;
              </li>
              <li>
                the User has engaged in prohibited conduct, fraud, misuse or
                suspicious activity;
              </li>
              <li>
                continued access poses legal, regulatory, financial or
                reputational risk to the Company;
              </li>
              <li>
                the User has provided false, misleading or incomplete
                information;
              </li>
              <li>
                suspension or termination is required by Applicable Law,
                regulatory direction or court order.
              </li>
            </ul>
            <p>
              <strong>12.2</strong> Suspension or restriction may include
              limitation of features, freezing of transactions, withholding of
              payouts or disabling of specific functionalities, without
              affecting the validity of prior Transactions.
            </p>
            <p>
              <strong>12.3</strong> The Company shall not be liable for any
              losses, damages, claims, compensation or business interruption
              arising from suspension, restriction or termination of access,
              including loss of profits, goodwill or data.
            </p>

            <p>
              <strong>12.4</strong> Termination of access shall not affect any
              rights, obligations or liabilities accrued prior to such
              termination, including payment obligations, indemnities and
              dispute resolution rights, which shall survive termination.
            </p>
            <p>
              <strong>12.5</strong> The Company reserves the right to retain and
              use data as required under Applicable Law, the Privacy Policy and
              for legitimate business or compliance purposes, notwithstanding
              suspension or termination.
            </p>
          </div>
        </section>

        {/* ARTICLE 13 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 13: DISCLAIMERS & WARRANTIES
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>13.1</strong> The Platform and all Services are provided
              on an <strong>"AS IS"</strong> and <strong>"AS AVAILABLE"</strong>{" "}
              basis. To the maximum extent permitted under Applicable Law,
              Spares Connect expressly disclaims all warranties of any kind,
              whether express, implied, statutory or otherwise.
            </p>
            <p>
              <strong>13.2</strong> Without limitation, Spares Connect disclaims
              any implied warranties of merchantability, fitness for a
              particular purpose, non-infringement, accuracy, reliability,
              availability, uninterrupted operation or error-free performance of
              the Platform or Services.
            </p>
            <p>
              <strong>13.3</strong> Spares Connect does not warrant or represent
              that:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>the Platform will meet User requirements or expectations;</li>
              <li>
                access to the Platform will be uninterrupted, timely, secure or
                error-free;
              </li>
              <li>
                information, listings, quotations or Content available on the
                Platform are accurate, complete or current.
              </li>
            </ul>
            <p>
              <strong>13.4</strong> All products listed or supplied through the
              Platform are offered by independent Sellers. Any warranties,
              guarantees, representations, recalls or after-sales obligations
              relating to products are provided{" "}
              <strong>solely by the respective Seller</strong>
              and not by Spares Connect.
            </p>
            <p>
              <strong>13.5</strong> Spares Connect does not provide any warranty
              or assurance regarding product quality, compatibility, safety,
              legality or fitness for any vehicle, application or use. Users
              acknowledge that automobile spare parts may be safety-critical and
              require independent technical verification prior to installation
              or use.
            </p>

            <p>
              <strong>13.6</strong> Spares Connect shall not be responsible for
              any reliance placed by Users on Platform Content, Seller
              information or third-party services, including payment or
              logistics services.
            </p>
          </div>
        </section>

        {/* ARTICLE 14 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 14: LIMITATION OF LIABILITY
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>14.1</strong> To the maximum extent permitted under
              Applicable Law, the total aggregate liability of Spares Connect,
              whether arising in contract, tort (including negligence),
              statutory duty or otherwise, shall be limited to the platform fees
              actually received by the Company in respect of the specific
              Transaction giving rise to the claim.
            </p>
            <p>
              <strong>14.2</strong> In no event shall Spares Connect be liable
              for any indirect, incidental, special, consequential, exemplary or
              punitive damages, including but not limited to loss of profits,
              loss of business, loss of goodwill, vehicle downtime, loss of data
              or any other economic or commercial loss, even if advised of the
              possibility of such damages.
            </p>
            <p>
              <strong>14.3</strong> Without prejudice to the foregoing, Spares
              Connect shall not be liable for any claims arising from:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>product defects, incompatibility or misuse;</li>
              <li>installation, handling or operation of spare parts;</li>
              <li>
                actions or omissions of Sellers, Buyers, payment partners or
                logistics providers;
              </li>
              <li>
                accidents, injuries or property damage related to vehicle usage.
              </li>
            </ul>
          </div>
        </section>

        {/* ARTICLE 15 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 15: INDEMNITY
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>15.1</strong> Each User agrees to indemnify, defend and
              hold harmless <strong>Spares Connect LLP</strong>, its partners,
              designated partners, affiliates, officers, employees and permitted
              representatives from and against any and all claims, demands,
              actions, proceedings, damages, losses, liabilities, penalties,
              fines, costs and expenses (including reasonable legal fees and
              costs) arising out of or relating to:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                the User's breach of these Terms or any applicable Policy;
              </li>
              <li>misuse of the Platform or Services;</li>
              <li>violation of Applicable Law or third-party rights;</li>
              <li>
                disputes between Buyers and Sellers, including product quality,
                delivery, payment or warranty disputes;
              </li>
              <li>submission, use or misuse of User Content;</li>
              <li>
                product defects, installation issues, accidents, injuries or
                property damage arising from goods supplied or procured through
                the Platform.
              </li>
            </ul>
            <p>
              <strong>15.2</strong> Spares Connect shall have the right, but not
              the obligation, to control the defence and settlement of any
              indemnified claim, at the User's cost, provided that no settlement
              admitting liability on behalf of Spares Connect shall be entered
              into without its prior written consent.
            </p>
            <p>
              <strong>15.3</strong> The indemnity of obligations under this
              Article shall survive suspension, termination or expiration of the
              User's access to the Platform.
            </p>
          </div>
        </section>
        {/* ARTICLE 16 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 16: FORCE MAJEURE
          </h2>
          <div className="space-y-5 text-base md:text-lg">
            <p>
              <strong>16.1</strong> Neither Spares Connect nor any User shall be
              liable for any delay, failure or interruption in performance of
              obligations under these Terms where such delay or failure results
              from events beyond reasonable control ("Force Majeure Event").
            </p>
            <p>
              <strong>16.2</strong> Force Majeure Events include, without
              limitation:
            </p>
            <ul className="list-disc pl-6 md:pl-8 space-y-2">
              <li>
                acts of God, natural disasters, floods, earthquakes, fires or
                pandemics;
              </li>
              <li>war, terrorism, riots, civil unrest or strikes;</li>
              <li>
                government orders, lockdowns, regulatory actions or court
                directions;
              </li>
              <li>
                failure or disruption of telecommunications, internet services,
                servers, power supply, banking systems, UPI or payment networks;
              </li>
              <li>
                failure or delays caused by third-party service providers,
                including payment partners or logistics providers.
              </li>
            </ul>
            <p>
              <strong>16.3</strong> During the continuance of a Force Majeure
              Event, the affected party's obligations shall be suspended for the
              duration of such event and performance shall resume as soon as
              reasonably practicable.
            </p>
            <p>
              <strong>16.4</strong> Spares Connect shall not be liable for any
              losses, damages or claims arising from or attributable to a Force
              Majeure Event.
            </p>
          </div>
        </section>

        {/* ARTICLE 17 */}
        <section>
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b border-gray-200 dark:border-gray-700 pb-3">
            ARTICLE 17: GOVERNING LAW & JURISDICTION
          </h2>
          <p className="text-base md:text-lg">
            These Terms and all disputes, claims or proceedings arising out of
            or relating to the Platform, the Services or Transactions shall be
            governed by and construed in accordance with the laws of India. The
            courts at <strong>Salem, Tamil Nadu,</strong> shall have{" "}
            <strong>exclusive jurisdiction</strong> over all such matters.
          </p>
        </section>
      </main>

    
    </div>
  );
};

export default Terms;
